# Generated by Django 4.0.6 on 2022-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_users_tokenn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tokenn',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
